from .models import Source


SOURCES = (
    Source(
        "AWS Blog",
        "Cloud & Infrastructure",
        "https://aws.amazon.com/blogs/aws/feed/",
        ("aws.amazon.com",),
        ("cloud",),
    ),
    Source(
        "Google Cloud Blog",
        "Cloud & Infrastructure",
        "https://cloudblog.withgoogle.com/rss/",
        ("cloud.google.com", "cloudblog.withgoogle.com"),
        ("cloud",),
    ),
    Source(
        "Azure Blog",
        "Cloud & Infrastructure",
        "https://azure.microsoft.com/en-us/blog/feed/",
        ("azure.microsoft.com",),
        ("cloud",),
    ),
    Source(
        "Cloudflare Blog",
        "Cloud & Infrastructure",
        "https://blog.cloudflare.com/rss/",
        ("blog.cloudflare.com",),
        ("cloud", "networking", "security", "web"),
    ),
    Source(
        "Kubernetes Blog",
        "DevOps & Reliability",
        "https://kubernetes.io/feed.xml",
        ("kubernetes.io",),
        ("cloud-native", "kubernetes", "open-source"),
    ),
    Source(
        "CNCF",
        "DevOps & Reliability",
        "https://www.cncf.io/feed/",
        ("cncf.io",),
        ("cloud-native", "open-source"),
    ),
    Source(
        "HashiCorp Blog",
        "DevOps & Reliability",
        "https://www.hashicorp.com/blog/feed.xml",
        ("hashicorp.com",),
        ("cloud", "dev-tools"),
    ),
    Source(
        "DevOps.com",
        "DevOps & Reliability",
        "https://devops.com/feed/",
        ("devops.com",),
        ("dev-tools", "observability"),
    ),
    Source(
        "OpenAI News",
        "AI & ML",
        "https://openai.com/news/rss.xml",
        ("openai.com",),
        ("ai", "research"),
    ),
    Source(
        "Hugging Face Blog",
        "AI & ML",
        "https://huggingface.co/blog/feed.xml",
        ("huggingface.co",),
        ("ai", "open-source"),
    ),
    Source(
        "Google DeepMind",
        "AI & ML",
        "https://deepmind.google/blog/rss.xml",
        ("deepmind.google",),
        ("ai", "research"),
    ),
    Source(
        "GitHub Engineering",
        "Software Engineering",
        "https://github.blog/engineering/feed/",
        ("github.blog",),
        ("dev-tools", "open-source", "programming"),
    ),
    Source(
        "Netflix TechBlog",
        "Software Engineering",
        "https://netflixtechblog.com/feed",
        ("netflixtechblog.com",),
        ("architecture", "databases", "programming"),
    ),
    Source(
        "Mozilla Hacks",
        "Software Engineering",
        "https://hacks.mozilla.org/feed/",
        ("hacks.mozilla.org",),
        ("open-source", "programming", "web"),
    ),
    Source(
        "InfoQ",
        "Software Engineering",
        "https://feed.infoq.com/",
        ("infoq.com",),
        ("architecture", "programming"),
    ),
    Source(
        "KrebsOnSecurity",
        "Security & Privacy",
        "https://krebsonsecurity.com/feed/",
        ("krebsonsecurity.com",),
        ("privacy", "security"),
    ),
    Source(
        "Google Project Zero",
        "Security & Privacy",
        "https://googleprojectzero.blogspot.com/feeds/posts/default",
        ("googleprojectzero.blogspot.com", "projectzero.googleblog.com"),
        ("research", "security"),
    ),
    Source(
        "IEEE Spectrum",
        "Hardware & Emerging Tech",
        "https://spectrum.ieee.org/feeds/feed.rss",
        ("spectrum.ieee.org",),
        ("hardware", "research"),
    ),
    Source(
        "Ars Technica",
        "General Tech",
        "https://feeds.arstechnica.com/arstechnica/technology-lab",
        ("arstechnica.com",),
    ),
    Source(
        "MIT Technology Review",
        "General Tech",
        "https://www.technologyreview.com/feed/",
        ("technologyreview.com",),
        ("research",),
    ),
)
